### ISSUE TITLE
About formula derivation

### ISSUE THREAD

**Issue by yuyu0927** [jasonyzhang/RayDiffusion#13]
Hi,

Amazing work!
Could you breifly introduce how to get equation (3) in your paper? Or You can just tell me what references I can look up. Thanks!!!

**Comment by jasonyzhang** [comment]
In equation 3, d is the unprojected ray through each u. The moment can be computed using o x d. We use the camera center as our o since every ray will pass through the camera center (-R.T @ t).

These notes are very helpful for understanding plucker coordinates: https://faculty.sites.iastate.edu/jia/files/inline-files/plucker-coordinates.pdf
